EAR_THRESHOLD = 0.18
GAZE_LEFT_THRESH = 0.25
GAZE_RIGHT_THRESH = 0.75
GAZE_HEAD_YAW_THRESH = 20.0
GAZE_HEAD_PITCH_THRESH = 20.0
YAW_THRESHOLD = 35.0
PITCH_THRESHOLD = 35.0
BUFFER_MINUTES = 5
PORT = 5000

# Cognitive State Engine Thresholds
CSI_BASE = 10.0
CSI_DISTRACTION_MULTIPLIER = 15
CSI_DISTRACTION_MAX = 45
CSI_DROWSINESS_MIN_DURATION = 0.5
CSI_DROWSINESS_MULTIPLIER = 25
CSI_DROWSINESS_MAX = 55
CSI_YAW_THRESHOLD = 20
CSI_YAW_PENALTY = 15
CSI_PITCH_THRESHOLD = 15
CSI_PITCH_PENALTY = 10
CSI_BPM_HIGH = 28
CSI_BPM_LOW = 6
CSI_BPM_PENALTY = 10
HYSTERESIS_MARGIN = 3